---
- name: Manage GNS3 devices - add ip sla
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: remove ip sla
      ios_config:
        lines:
          - no ip sla 1

    - name: configure ip sla
      ios_config:
        authorize: yes
        parents: ip sla 1
        lines:
          - icmp-echo 192.168.240.137 source-interface GigabitEthernet0/0
          - vrf Mgmt-intf
          - frequency 10
          - ip sla schedule 1 life forever start-time now

    - name: show ip sla summary
      ios_command:
        commands:
          -  show ip sla summary

      register: print_output

    -  debug: var=print_output
    
- name: Manage GNS3 devices - sh vrf interfaces
  hosts: all
  gather_facts: false
  connection: local

  tasks:
      - name: show vrf interfaces / ip interface
        ios_command:
        commands:
          -  show ip interface brief
          -  show ip vrf interfacce
      register: print_output

    -  debug: var=print_output
          
