---
- name: Manage GNS3 devices configure l2 switch
  hosts: S1
  gather_facts: false
  connection: local
  tasks:
    - name: Interface Settings
      ios_config:
         parents:
           - interface {{ item.interface }}
         lines:
           - switchport access vlan {{ item.vlan }}
           - switchport voice vlan {{ item.voice_vlan }}
           - switchport host
           - switchport port-security maximum 2
           - switchport port-security
           - switchport port-security aging time 2
           - switchport port-security aging type inactivity
           - switchport port-security violation restrict
           - ip arp inspection limit rate 100
           - ip dhcp snooping limit rate 100
         after:
           - no shutdown
      with_items:
        - { interface : GigabitEthernet0/0, vlan : 100, voice_vlan : 101 }
        - { interface : GigabitEthernet1/0, vlan : 10, voice_vlan : 101 }
        - { interface : GigabitEthernet2/0, vlan : 20, voice_vlan : 101 }
        - { interface : GigabitEthernet3/0, vlan : 30, voice_vlan : 101 }
      register: print_output
    -  debug: var=print_output
